type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword
model=old_flail
nbt.display.Name=iregex:(\u0421\u0442\u0430\u0440\u044b\u0439\u0020\u043a\u0438\u0441\u0442\u0435\u043d\u044c|Old Flail)
#Старый кистень