type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword
model=eviction_notice
nbt.display.Name=iregex:(\u0421\u0020\u0432\u0435\u0449\u0430\u043c\u0438\u0020\u043d\u0430\u0020\u0432\u044b\u0445\u043e\u0434|Eviction Notice)
#С вещами на выход