type=item
matchItems=netherite_sword
model=valkiryes_whisper
nbt.display.Name=iregex:(\u0428\u0435\u043f\u043e\u0442 \u0432\u0430\u043b\u044c\u043a\u0438\u0440\u0438\u0438|Valkirye's Whisper)
#Шепот валькирии