items=wooden_sword stone_sword golden_sword iron_sword diamond_sword netherite_sword
model=enlightener
nbt.display.Name=iregex:(\u0412\u0440\u0430\u0437\u0443\u043c\u0438\u0442\u0435\u043b\u044c|Enlightener)
#Вразумитель