type=item
matchItems=wooden_sword stone_sword iron_sword golden_sword diamond_sword netherite_sword
texture=glass_shard
model=optifine/cit/source_models/1xhand
nbt.display.Name=iregex:(\u041e\u0441\u043a\u043e\u043b\u043e\u043a\u0020\u0441\u0442\u0435\u043a\u043b\u0430|Glass Shard)
#Осколок стекла